// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okdhttbclsbduystgofj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rZGh0dGJjbHNiZHV5c3Rnb2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMDgyMzMsImV4cCI6MjA2Njc4NDIzM30.PU20E9h_Pv9eS5hCWW2UeWGX7EhyWGDsNNKC4lKiB4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);